---
image: docker:latest
services:
- docker:dind
stages:
- build
- deploy

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build math:
  stage: build
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /master|develop/
  tags:
    - docker

deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Production --stack polis-prod --service polis-math --new-image $RELEASE_IMAGE --no-finish-upgrade
  only:
    - /master/
  environment: production
  tags:
    - docker

deploy to development:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Production --stack polis-dev --service polis-math --new-image $RELEASE_IMAGE --no-finish-upgrade
  only:
    - /develop/
  environment: development
  tags:
    - docker
