---
image: docker:17.04-git
services:
- docker:17.04-dind
stages:
- build

variables:
  IMAGE_NAME: registry.gitlab.com/empurrandojuntos/polismath

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build to production:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_BUILD_REF_NAME
    - docker push $IMAGE_NAME:$CI_BUILD_REF_NAME
  only:
    - /master/
  environment: production
  tags:
    - docker
