---
image: docker:17.04-git
services:
- docker:17.04-dind
stages:
- build

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE/node:$CI_BUILD_REF_NAME

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build to production:
  stage: build
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "CI_REGISTRY_IMAGE:latest"
  only:
    - /master/
  environment: production
  tags:
    - docker
